site_name: 'devopsday'
site_description: 'Main documentation for the devopsday'
repo_url: https://github.com/pkill-2913/devopsday
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'